version: "3.8"
services:
  db:
    image: postgres
    container_name: db_sheets
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pwd1234
      POSTGRES_DB: sheets_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
